Repository kingsleyadam/local-abbfreeathome, pull requests merged in 2024-11, with the labels that each got.

#80 Implement RTC
  src/abbfreeathome/const.py
  src/abbfreeathome/devices/room_temperature_controller.py
  tests/test_room_temperature_controller.py
Labels: enhancement

#79 Implement new device - Blind Actuator
  src/abbfreeathome/const.py
  src/abbfreeathome/devices/cover_actuator.py
  tests/test_cover_actuator.py
Labels: enhancement, Semver-Minor

#81 Add additional switch sensors functions
  src/abbfreeathome/const.py
Labels: enhancement, Semver-Minor

#84 Bugfix RTC-valve
  src/abbfreeathome/devices/room_temperature_controller.py
  tests/test_room_temperature_controller.py
Labels: bug, Semver-Patch

#89 Catch ClientConnectionError exceptions
  src/abbfreeathome/api.py
  src/abbfreeathome/exceptions.py
  tests/test_api.py
Labels: enhancement, Semver-Minor

#97 Implement Forced Option
  src/abbfreeathome/devices/dimming_actuator.py
  src/abbfreeathome/devices/switch_actuator.py
  tests/test_dimming_actuator.py
  tests/test_switch_actuator.py
Labels: enhancement, Semver-Minor

#106 Fix unboundlocalerror
  src/abbfreeathome/devices/base.py
  tests/test_base.py
Labels: bug, Semver-Patch

#115 Adjust Forced Position for Easier Integration
  src/abbfreeathome/devices/cover_actuator.py
  src/abbfreeathome/devices/dimming_actuator.py
  src/abbfreeathome/devices/switch_actuator.py
  tests/test_cover_actuator.py
  tests/test_dimming_actuator.py
  tests/test_switch_actuator.py
Labels: enhancement

#123 Refactor FreeAtHomeApi Session Logic
  src/abbfreeathome/api.py
  tests/test_api.py
Labels: enhancement

#124 Allow for passing in a session to FreeAtHomeSettings
  src/abbfreeathome/api.py
  tests/test_api.py
Labels: enhancement

#126 Fix client session on FreeAtHomeSettings
  pyproject.toml
  src/abbfreeathome/api.py
Labels: bug

#127 Log all websocket responses to debug
  pyproject.toml
  src/abbfreeathome/api.py
Labels: Semver-Patch

#131 Add new property for whether sysap has api support
  src/abbfreeathome/api.py
  tests/test_api.py
Labels: enhancement

#135 Fix websocket example, add packaging requirement
  README.md
  pyproject.toml
  src/abbfreeathome/dev-requirements.txt
Labels: bug
