Repository kingsleyadam/local-abbfreeathome, pull requests merged in 2025-07, with the labels that each got.

#196 Additional Refactor - Code Clean-Up
  README.md
  src/abbfreeathome/device.py
  src/abbfreeathome/freeathome.py
  tests/test_device.py
  tests/test_device_channel_composition.py
  tests/test_freeathome.py
Labels: breaking-change

#198 Adds new FreeAtHomeFloorPlan class, reduce API requests
  .github/workflows/publish.yaml
  pyproject.toml
  src/abbfreeathome/api.py
  src/abbfreeathome/device.py
  src/abbfreeathome/floorplan.py
  src/abbfreeathome/freeathome.py
  tests/conftest.py
  tests/test_api.py
  tests/test_device.py
  tests/test_device_channel_composition.py
  tests/test_floorplan.py
  tests/test_freeathome.py
Labels: breaking-change

#199 Adjust channel floor/room name assignment
  src/abbfreeathome/device.py
Labels: bug

#200 Add FID_DES_LEVEL_CALL_SENSOR for DesDoorRingingSensor
  src/abbfreeathome/const.py
Labels: enhancement

#204 Adds new function `get_channels_by_device` to FreeAtHome
  pyproject.toml
  src/abbfreeathome/freeathome.py
  tests/test_freeathome.py
Labels: enhancement

#213 Adjust .gitignore to ignore tests_* files in the root of the repo only
  .gitignore
Labels: bug

#209 Implement virtual room temperature controller
  src/abbfreeathome/channels/virtual/virtual_room_temperature_controller.py
  src/abbfreeathome/const.py
  tests/test_virtual_room_temperature_controller.py
Labels: enhancement

#215 Implement Welcome IP Mute Actuator/Sensor
  src/abbfreeathome/channels/switch_actuator.py
  src/abbfreeathome/const.py
Labels: enhancement

#216 Added support for locking of movement detectors
  README.md
  src/abbfreeathome/channels/movement_detector.py
  src/abbfreeathome/const.py
  tests/test_movement_detector.py
Labels: enhancement

#217 Create class alias for SimpleSwitchActuator
  pyproject.toml
  src/abbfreeathome/channels/switch_actuator.py
  src/abbfreeathome/const.py
Labels: enhancement
